### ISSUE TITLE
libfilecoin.a 这个库您使用官方的编译的吗

### ISSUE THREAD

**Issue by ChenDeChickenDinner** [SzeChuanChilliSauce/lotus-addr-tools#1]
libfilecoin.a 貌似没有真机的

**Comment by SzeChuanChilliSauce** [comment]
真机的是什么意思？这是库是编译lotus时，编译出的第三方库，bls相关的功能。

**Comment by ChenDeChickenDinner** [comment]
我用lipo -info libfilecoin.a 输出是这样的：
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/33922521/83586727-d28b5e00-a57f-11ea-8134-12bc6ba22d17.png">

没有找到如: arm64、armv7、arm7s等可以在iOS真机中使用的架构。
您编译出来的这个静态库我可以在iOS真机中使用吗？

**Comment by ChenDeChickenDinner** [comment]
@SzeChuanChilliSauce

**Comment by SzeChuanChilliSauce** [comment]
我这个pc上的，ubuntu18.04，如果你要在ios上使用，要编译成对应平台的库。
