### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by apple94586** [SzeChuanChilliSauce/lotus-addr-tools#2]
➜  lotus-addr-tools git:(master) make 
gcc -c addr.c blake2b.c ecc_key.c encode.c main.c random.c
In file included from ecc_key.c:1:
./ecc_key.h:6:10: fatal error: 'bits/stdint-uintn.h' file not found
#include <bits/stdint-uintn.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from main.c:11:
./ecc_key.h:6:10: fatal error: 'bits/stdint-uintn.h' file not found
#include <bits/stdint-uintn.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from random.c:1:
./random.h:11:10: fatal error: 'bits/stdint-uintn.h' file not found
#include <bits/stdint-uintn.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [xxx] Error 1
➜  lotus-addr-tools git:(master) ✗ make 
gcc -c 
clang: error: no input files
make: *** [xxx] Error 1
➜  lotus-addr-tools git:(master) ✗

**Comment by SzeChuanChilliSauce** [comment]
I compile it on Ubuntu18.04. It's ok.
